### ISSUE TITLE
Prune option, as mentioned in telegram convo.

### ISSUE THREAD

**Issue by wildfunctions** [EOS-Nation/eosvotes-demux-tally#1]
Just a thought

If a `PRUNE_BY_ACTION` var was set in config, and if `collectActionsFromBlock` in https://github.com/EOS-Nation/eosvotes-demux-tally/blob/master/demux-js/demux/readers/eos/NodeosBlock.ts#L16 could check against the `actionType` lists in updaters.ts, I think that'd be sufficient for saving some disk space.

**Comment by DenisCarriere** [comment]
👍 definitely need a way to Prune actions to save disk space.

I'm going to implement contract blacklist that prevents `accounts` from being stored in the local cache, this should also speed things up for re-syncing.

**.env**

```env
DEMUX_CONTRACT_BLACKLIST="blocktwitter,chaintwitter"
```
